#!/usr/bin/env escript

tick() ->
    {_, Secs, _} = now(),
    tick(Secs).

tick(Secs) ->
    {_, S, _} = now(),
    io:format("~~tick~~  ~p~n", [S-Secs]),
    timer:sleep(1000),
    tick(Secs).

sink() ->
    receive Term -> io:format("Received: ~p~n", [Term]) end,
    sink().

good_sleep(_Dst, 0) ->
    ok;
good_sleep(Dst, N) when N > 0 ->
    spawn(fun() -> goodnif:delayed_send(Dst, N, 4) end),
    good_sleep(Dst, N-1).

main(_) ->
    spawn(fun() -> tick() end),
    good_sleep(spawn(fun() -> sink() end), 8),
    timer:sleep(10000).
