#!/usr/bin/env escript

receiver(Dst) ->
    receive
        {MyTerm, Ptr} ->
            MyTerm = termptr:unwrap(Ptr)
    end,
    Dst ! ok.


main([]) ->
    Self = self(),
    MyTerm = [{foo, bar}, 1.3, Self, make_ref()],
    Ptr = termptr:wrap(MyTerm),
    MyTerm = termptr:unwrap(Ptr),
    Pid = spawn(fun() -> receiver(Self) end),
    Pid ! {MyTerm, Ptr},
    receive
        ok -> ok
    end.
